[AMQP]


# Host information
# # scheme://username:password@host:port/vhost
url = "amqps://amqpusername:amqppassword@amqp.exapmle.com:5671/vhost"

# Exchange to listen for raw records
exchange = 'gracc.osg.raw'

# Queue to use to listen to raw records
queue = 'gracc.osg.archive'

[Directories]

# Location of in-progress tarfiles should be written.
sandbox = 'sandbox'

# Output location of finalized tarball
output = 'output'

